// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH3UHipfMdlcKNWWZtglLXdPFw-W2dv7U',
    appId: '1:256975320455:web:52e5846c475396077c0f22',
    messagingSenderId: '256975320455',
    projectId: 'carapp2026-57b5c',
    authDomain: 'carapp2026-57b5c.firebaseapp.com',
    databaseURL: 'https://carapp2026-57b5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carapp2026-57b5c.firebasestorage.app',
    measurementId: 'G-G19Q4824X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_rlZ6li4wy5UiXkOICTscwnFXqaKHumc',
    appId: '1:256975320455:android:5d4b8264694a0dfd7c0f22',
    messagingSenderId: '256975320455',
    projectId: 'carapp2026-57b5c',
    databaseURL: 'https://carapp2026-57b5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carapp2026-57b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi46arU4DTsR2CVpsAXAYh8Mqhvu6KqnA',
    appId: '1:256975320455:ios:7361a5aaa33d58ec7c0f22',
    messagingSenderId: '256975320455',
    projectId: 'carapp2026-57b5c',
    databaseURL: 'https://carapp2026-57b5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carapp2026-57b5c.firebasestorage.app',
    iosBundleId: 'com.example.myProj2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi46arU4DTsR2CVpsAXAYh8Mqhvu6KqnA',
    appId: '1:256975320455:ios:7361a5aaa33d58ec7c0f22',
    messagingSenderId: '256975320455',
    projectId: 'carapp2026-57b5c',
    databaseURL: 'https://carapp2026-57b5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carapp2026-57b5c.firebasestorage.app',
    iosBundleId: 'com.example.myProj2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH3UHipfMdlcKNWWZtglLXdPFw-W2dv7U',
    appId: '1:256975320455:web:35dd568ce1e401b67c0f22',
    messagingSenderId: '256975320455',
    projectId: 'carapp2026-57b5c',
    authDomain: 'carapp2026-57b5c.firebaseapp.com',
    databaseURL: 'https://carapp2026-57b5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carapp2026-57b5c.firebasestorage.app',
    measurementId: 'G-Y15LBMDYGR',
  );
}
